import { card } from "./builder";

export const AR_CARDS = [
  card({
    id: "ar-ijtimae", languageId: "ar", deckIds: ["deck-ar-msa"],
    word: "ijtimāʿ", nativeScript: "اجتماع", translation: "meeting",
    partOfSpeech: "noun", cefr: "B1", topic: "Business", difficulty: 3, frequency: 4,
    pronunciation: "ij-ti-MAA3", ipa: "/id͡ʒ.tiˈmaːʕ/", romanization: "ijtimāʿ",
    gender: "masculine", plural: "اجتماعات (ijtimāʿāt)",
    collocations: ["عقد اجتماعاً (to hold a meeting)", "حضر الاجتماع (attended the meeting)"],
    synonyms: ["لقاء (liqāʾ)"], antonyms: [],
    relatedWords: ["اجتمع (to meet)", "مجتمع (society)", "جماعة (group)"],
    memoryTips: "Root ج-م-ع (j-m-ʿ) = gathering. Ijtimāʿ, mujtamaʿ (society), jamāʿa (group) — one root, one family.",
    commonMistakes: "Learners confuse اجتماع (a meeting) with مجتمع (society) — same root, different pattern.",
    grammarNotes: "Form VIII verbal noun (iftiʿāl pattern) from اجتمع.",
    usageNotes: "Standard across all Arab countries for formal meetings.",
    register: "formal",
    examples: [
      { native: "لدينا اجتماع مهم غداً صباحاً.", translation: "We have an important meeting tomorrow morning.", explanation: "Romanized: 'ladaynā ijtimāʿ muhimm ghadan ṣabāḥan'.", whyUseful: "The bread-and-butter sentence of Arabic office life." },
      { native: "عُقد الاجتماع في القاعة الرئيسية.", translation: "The meeting was held in the main hall.", explanation: "Passive verb عُقد (was held) — common in formal reports.", whyUseful: "Teaches the formal passive used in news and minutes." },
      { native: "تأجل الاجتماع إلى الأسبوع القادم.", translation: "The meeting was postponed to next week.", explanation: "'taʾajjala' = was postponed; 'al-usbūʿ al-qādim' = next week.", whyUseful: "Rescheduling vocabulary you'll genuinely need." },
    ],
  }),
  card({
    id: "ar-sabr", languageId: "ar", deckIds: ["deck-ar-quran"],
    word: "ṣabr", nativeScript: "صبر", translation: "patience / perseverance",
    partOfSpeech: "noun", cefr: "B1", topic: "Values", difficulty: 2, frequency: 5,
    pronunciation: "SSAB-r (emphatic S)", ipa: "/sˤabr/", romanization: "ṣabr",
    gender: "masculine",
    collocations: ["الصبر مفتاح الفرج (patience is the key to relief)", "بفارغ الصبر (impatiently)"],
    synonyms: ["تحمل (taḥammul)"], antonyms: ["جزع (jazaʿ)"],
    relatedWords: ["صابر (patient person)", "اصطبر (to persevere)"],
    memoryTips: "The emphatic ṣād gives it weight — patience is heavy to carry. Ṣabr = 'suppressed' urgency.",
    commonMistakes: "ṣabr (صبر) with emphatic ṣād vs sabr with plain s — the emphatic consonant changes the word entirely.",
    culturalNotes: "Central concept in the Quran — mentioned over 100 times. 'إن الله مع الصابرين' (God is with the patient) is universally known.",
    grammarNotes: "Verbal noun (maṣdar) of صَبَرَ.",
    usageNotes: "'bi-fārigh al-ṣabr' (with emptied patience) idiomatically means 'eagerly'.",
    register: "neutral",
    examples: [
      { native: "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", translation: "Indeed, God is with the patient. (Quran 2:153)", explanation: "The active participle صابرين (those who are patient) in the plural.", whyUseful: "One of the most quoted Quranic phrases in daily life." },
      { native: "الصبر مفتاح الفرج.", translation: "Patience is the key to relief.", explanation: "A proverb: ṣabr + muftāḥ (key) + faraj (relief).", whyUseful: "Universally used to comfort someone facing difficulty." },
      { native: "أنتظر نتيجة الامتحان بفارغ الصبر.", translation: "I'm waiting for the exam result impatiently.", explanation: "'bi-fārigh al-ṣabr' — a fixed idiom meaning eagerly.", whyUseful: "An elegant idiom that lifts your Arabic above textbook level." },
    ],
  }),
  card({
    id: "ar-tawakkul", languageId: "ar", deckIds: ["deck-ar-quran"],
    word: "tawakkul", nativeScript: "توكل", translation: "trust / reliance (on God)",
    partOfSpeech: "noun", cefr: "B2", topic: "Values", difficulty: 3, frequency: 3,
    pronunciation: "ta-WAK-kul", ipa: "/taˈwak.kul/", romanization: "tawakkul",
    gender: "masculine",
    collocations: ["التوكل على الله (reliance upon God)"],
    synonyms: ["اعتماد (iʿtimād)"], antonyms: [],
    relatedWords: ["وكيل (agent/trustee)", "توكيل (power of attorney)", "اتكل (to lean on)"],
    memoryTips: "Root و-ك-ل = entrusting. A wakīl is your trustee; tawakkul is making God your wakīl.",
    commonMistakes: "tawakkul (trust in God after doing your part) ≠ tawākul (passive laziness) — one vowel flips the meaning to its opposite.",
    culturalNotes: "Famous hadith: 'Tie your camel, then trust in God' — tawakkul means effort first, then trust.",
    grammarNotes: "Form V verbal noun (tafaʿʿul pattern).",
    register: "formal",
    examples: [
      { native: "وَعَلَى اللَّهِ فَتَوَكَّلُوا إِن كُنتُم مُّؤْمِنِينَ", translation: "And upon God rely, if you are believers. (Quran 5:23)", explanation: "Imperative توكلوا with the object fronted for emphasis.", whyUseful: "Shows classical word order used for rhetorical emphasis." },
      { native: "اعقلها وتوكل.", translation: "Tie it (your camel) and trust in God.", explanation: "From the famous hadith — effort plus trust.", whyUseful: "A cultural touchstone quoted in everyday decision-making." },
      { native: "الفرق كبير بين التوكل والتواكل.", translation: "There is a big difference between reliance and complacency.", explanation: "Contrasts tawakkul with its lazy cousin tawākul.", whyUseful: "Drills the exact minimal pair natives use in sermons and talks." },
    ],
  }),
  card({
    id: "ar-mawid", languageId: "ar", deckIds: ["deck-ar-msa"],
    word: "mawʿid", nativeScript: "موعد", translation: "appointment / scheduled time",
    partOfSpeech: "noun", cefr: "A2", topic: "Daily Life", difficulty: 2, frequency: 5,
    pronunciation: "MAW-3id", ipa: "/ˈmaw.ʕid/", romanization: "mawʿid",
    gender: "masculine", plural: "مواعيد (mawāʿīd)",
    collocations: ["حدد موعداً (to set an appointment)", "في الموعد (on time)"],
    synonyms: [], antonyms: [],
    relatedWords: ["وعد (promise)", "وعد (to promise)"],
    memoryTips: "From وعد (promise): a mawʿid is a promised time. An appointment is literally a promise of time.",
    commonMistakes: "Broken plural: mawāʿīd, not 'mawʿidāt'. Learners regularize it — natives never do.",
    grammarNotes: "Noun of place/time (mafʿil pattern) from the root و-ع-د.",
    usageNotes: "Used for doctor's appointments, deadlines, and even romantic dates in some dialects.",
    register: "neutral",
    examples: [
      { native: "عندي موعد مع الطبيب الساعة الرابعة.", translation: "I have a doctor's appointment at four o'clock.", explanation: "Romanized: 'ʿindī mawʿid maʿa al-ṭabīb al-sāʿa al-rābiʿa'.", whyUseful: "The exact sentence for one of life's most common errands." },
      { native: "وصل في الموعد المحدد تماماً.", translation: "He arrived exactly on time.", explanation: "'fī al-mawʿid al-muḥaddad' = at the specified time.", whyUseful: "Praising punctuality — useful in professional Arabic." },
      { native: "أرجو تأكيد الموعد قبل يوم واحد.", translation: "Please confirm the appointment one day in advance.", explanation: "'arjū' (I request) — polite formal opener.", whyUseful: "Template for polite scheduling emails and messages." },
    ],
  }),
];
