import { card } from "./builder";

export const DARIJA_CARDS = [
  card({
    id: "dj-bghit", languageId: "darija", deckIds: ["deck-dj-travel"],
    word: "bghit", nativeScript: "بغيت", translation: "I want",
    partOfSpeech: "verb", cefr: "A1", topic: "Essentials", difficulty: 1, frequency: 5,
    pronunciation: "b-GHEET (gh like French r)", ipa: "/bɣit/", romanization: "bghit",
    collocations: ["bghit nemchi (I want to go)", "bghit atay (I want tea)"],
    synonyms: [], antonyms: ["mabghitch (I don't want)"],
    relatedWords: ["ma bghitch", "kanbghi (I love/like)"],
    memoryTips: "Sounds like 'big heat' said fast — when you WANT something badly, you feel the big heat.",
    commonMistakes: "In Standard Arabic you'd say 'urīdu' — using it in Morocco sounds bookish. Darija speakers always say 'bghit'.",
    culturalNotes: "'Kanbghik' (from the same root) means 'I love you' in Darija.",
    grammarNotes: "Past-form verb used with present meaning. Negation wraps the verb: ma-bghit-ch.",
    usageNotes: "Follow with a noun (bghit atay) or another verb (bghit nemchi = I want to go).",
    register: "casual",
    examples: [
      { native: "بغيت واحد أتاي بالنعناع عافاك", translation: "I'd like a mint tea, please.", explanation: "Romanized: 'bghit wa7ed atay b-n3na3 3afak'. '3afak' = please.", whyUseful: "The number one sentence for any Moroccan café." },
      { native: "بغيت نمشي للسوق", translation: "I want to go to the souk.", explanation: "Romanized: 'bghit nemchi l-souq'. Verb chains: bghit + n-prefix verb.", whyUseful: "Template for expressing any intention: bghit + n-verb." },
      { native: "ما بغيتش هاد الشي", translation: "I don't want this.", explanation: "Romanized: 'ma bghitch had chi'. Negation with ma...ch around the verb.", whyUseful: "Politely refusing is essential in markets — this is how." },
    ],
  }),
  card({
    id: "dj-bshhal", languageId: "darija", deckIds: ["deck-dj-travel"],
    word: "bch7al", nativeScript: "بشحال", translation: "how much (price)",
    partOfSpeech: "adverb", cefr: "A1", topic: "Shopping", difficulty: 1, frequency: 5,
    pronunciation: "bsh-HAL", ipa: "/bʃħal/", romanization: "bch7al",
    collocations: ["bch7al hada? (how much is this?)", "bch7al l-kilo?"],
    synonyms: [], antonyms: [],
    relatedWords: ["ghali (expensive)", "rkhis (cheap)", "taman (price)"],
    memoryTips: "B-shhal — imagine asking 'by how (much) shall' I get this?",
    commonMistakes: "Standard Arabic 'bikam' won't get you far in a Moroccan souk — vendors expect 'bch7al'.",
    culturalNotes: "Haggling is expected in souks; opening with 'bch7al' in Darija instantly earns better prices than French or English.",
    usageNotes: "The '7' in romanization is the deep 'ḥ' sound — like fogging a mirror.",
    register: "casual",
    examples: [
      { native: "بشحال هادا؟", translation: "How much is this?", explanation: "Romanized: 'bch7al hada?' — hada = this (masculine).", whyUseful: "You will say this ten times a day in any Moroccan market." },
      { native: "بشحال الكيلو ديال البرتقال؟", translation: "How much is a kilo of oranges?", explanation: "Romanized: 'bch7al l-kilo dyal l-bortoqal?'. 'dyal' = of.", whyUseful: "'Dyal' is the glue of Darija possession — this drills it." },
      { native: "غالي بزاف! نقص شوية", translation: "Too expensive! Lower it a bit.", explanation: "Romanized: 'ghali bezzaf! n9es chwiya'. bezzaf = a lot, chwiya = a little.", whyUseful: "The classic haggling comeback after hearing the price." },
    ],
  }),
  card({
    id: "dj-bezzaf", languageId: "darija", deckIds: ["deck-dj-travel"],
    word: "bezzaf", nativeScript: "بزاف", translation: "a lot / very / too much",
    partOfSpeech: "adverb", cefr: "A1", topic: "Essentials", difficulty: 1, frequency: 5,
    pronunciation: "bez-ZAF", ipa: "/bəzzaf/", romanization: "bezzaf",
    collocations: ["zwin bezzaf (very beautiful)", "ghali bezzaf (too expensive)"],
    synonyms: [], antonyms: ["chwiya (a little)"],
    relatedWords: ["chwiya", "kter (more)"],
    memoryTips: "Imagine a 'buzz off' of bees — a LOT of them.",
    commonMistakes: "Standard Arabic 'kathīran' or 'jiddan' sound formal; in Morocco it's always 'bezzaf'.",
    culturalNotes: "One of the most Moroccan words there is — using it signals real Darija, not textbook Arabic.",
    usageNotes: "Goes after the adjective: zwin bezzaf (very nice), never bezzaf zwin.",
    register: "casual",
    examples: [
      { native: "المغرب زوين بزاف", translation: "Morocco is very beautiful.", explanation: "Romanized: 'l-Maghrib zwin bezzaf'. Adjective + bezzaf order.", whyUseful: "A guaranteed smile from any Moroccan you say it to." },
      { native: "كنعيا بزاف فالخدمة", translation: "I get very tired at work.", explanation: "Romanized: 'kan3ya bezzaf f-l-khedma'. khedma = work/job.", whyUseful: "Small talk about work — universal conversation topic." },
      { native: "شكرا بزاف!", translation: "Thanks a lot!", explanation: "Romanized: 'choukran bezzaf!'", whyUseful: "The warmest everyday thank-you in Morocco." },
    ],
  }),
  card({
    id: "dj-wakha", languageId: "darija", deckIds: ["deck-dj-travel"],
    word: "wakha", nativeScript: "واخا", translation: "okay / alright",
    partOfSpeech: "interjection", cefr: "A1", topic: "Essentials", difficulty: 1, frequency: 5,
    pronunciation: "WA-kha (kh like Scottish loch)", ipa: "/waχa/", romanization: "wakha",
    collocations: ["wakha wakha (okay okay)", "wakha a sidi (alright, sir)"],
    synonyms: ["safi (done/enough)"], antonyms: ["la (no)"],
    relatedWords: ["safi", "yallah (let's go)"],
    memoryTips: "Sounds like 'wow-kha' — wow, OK!",
    commonMistakes: "It can also mean 'even if' at the start of a clause — context decides.",
    culturalNotes: "Possibly the most-used word in Morocco. Agreeing with 'wakha' instead of French 'd'accord' marks you as a Darija speaker.",
    usageNotes: "Standalone agreement, or clause-initial for 'even though'.",
    register: "casual",
    examples: [
      { native: "— نتلاقاو غدا فالتمنية؟ — واخا", translation: "— Meet tomorrow at eight? — Okay.", explanation: "Romanized: '— ntla9aw ghedda f-tmenya? — wakha'.", whyUseful: "Minimal, natural agreement in everyday plans." },
      { native: "واخا غالي، غاديشريه", translation: "Even though it's expensive, I'll buy it.", explanation: "Romanized: 'wakha ghali, ghadi nchrih'. Clause-initial wakha = even if.", whyUseful: "Unlocks the second grammatical use of the same word." },
      { native: "واخا صافي، ماشي مشكل", translation: "Alright fine, no problem.", explanation: "Romanized: 'wakha safi, machi mochkil'.", whyUseful: "Three high-frequency words in one natural sentence." },
    ],
  }),
  card({
    id: "dj-lmaqla", languageId: "darija", deckIds: ["deck-dj-restaurant"],
    word: "l-me9la", nativeScript: "المقلة", translation: "tagine pan / frying dish",
    partOfSpeech: "noun", cefr: "A2", topic: "Food", difficulty: 2, frequency: 3,
    pronunciation: "l-MER-la (q as glottal)", ipa: "/lməqla/", romanization: "l-me9la",
    gender: "feminine",
    collocations: ["me9la dyal l7out (fried fish platter)"],
    synonyms: [], antonyms: [],
    relatedWords: ["tajin", "l7out (fish)", "meqli (fried)"],
    memoryTips: "The '9' romanizes the deep 'q' — think 'MECCA-la' pan sizzling.",
    commonMistakes: "A 'me9la' of fish is a fried-fish platter, not a cooking pot — menu vocabulary, not kitchenware, in restaurants.",
    culturalNotes: "Coastal Moroccan restaurants serve 'me9la' platters of assorted fried fish — a must-try in Essaouira.",
    register: "casual",
    examples: [
      { native: "عطيني واحد المقلة ديال الحوت", translation: "Give me one fried fish platter.", explanation: "Romanized: '3tini wa7ed l-me9la dyal l7out'.", whyUseful: "Orders the signature coastal dish like a local." },
      { native: "المقلة فهاد الريسطو بنينة بزاف", translation: "The fried fish here is delicious.", explanation: "Romanized: 'l-me9la f had l-resto bnina bezzaf'. bnina = tasty (fem).", whyUseful: "Complimenting food warmly is big in Moroccan culture." },
      { native: "شحال المقلة الكبيرة؟", translation: "How much is the large platter?", explanation: "Romanized: 'ch7al l-me9la l-kbira?'.", whyUseful: "Combines food + price vocabulary for real restaurant use." },
    ],
  }),
];
