import { card } from "./builder";

export const EN_CARDS = [
  card({
    id: "en-leverage", languageId: "en-pro", deckIds: ["deck-en-meetings"],
    word: "leverage", translation: "to use something to maximum advantage",
    partOfSpeech: "verb", cefr: "C1", topic: "Business Strategy", difficulty: 3, frequency: 5,
    pronunciation: "LEV-er-ij", ipa: "/ˈlev.ər.ɪdʒ/",
    collocations: ["leverage our expertise", "leverage data", "leverage a relationship"],
    synonyms: ["utilize", "capitalize on", "exploit"], antonyms: ["squander", "waste"],
    relatedWords: ["lever", "leveraged buyout", "leverage ratio"],
    memoryTips: "A lever multiplies force — to leverage something is to multiply its value.",
    commonMistakes: "Overuse makes writing sound like corporate jargon. In plain contexts, 'use' is often better; reserve 'leverage' for strategic advantage.",
    usageNotes: "As a noun in finance it means debt; as a verb in business it means exploiting an advantage.",
    register: "formal",
    examples: [
      { native: "We can leverage our existing customer base to launch the new product.", translation: "—", explanation: "Classic strategic use: an existing asset multiplied into new value.", whyUseful: "The archetypal usage in strategy meetings and pitch decks." },
      { native: "She leveraged her network to land three interviews in a week.", translation: "—", explanation: "Applied to personal career capital.", whyUseful: "Shows the word outside pure corporate strategy — great for interviews." },
      { native: "The company is over-leveraged and vulnerable to rate hikes.", translation: "—", explanation: "Financial sense: carrying too much debt.", whyUseful: "You'll misread financial news without knowing this second meaning." },
    ],
  }),
  card({
    id: "en-streamline", languageId: "en-pro", deckIds: ["deck-en-meetings"],
    word: "streamline", translation: "to make a process simpler and more efficient",
    partOfSpeech: "verb", cefr: "B2", topic: "Operations", difficulty: 2, frequency: 4,
    pronunciation: "STREEM-line", ipa: "/ˈstriːm.laɪn/",
    collocations: ["streamline operations", "streamline the workflow", "streamline approval processes"],
    synonyms: ["simplify", "optimize", "rationalize"], antonyms: ["complicate", "bloat"],
    relatedWords: ["efficiency", "lean", "bottleneck"],
    memoryTips: "Picture a fish's streamlined body — water flows past with zero friction. A streamlined process has zero friction.",
    commonMistakes: "'Streamline' already implies improvement — 'streamline and improve' is redundant.",
    usageNotes: "Almost always followed by a process-noun: operations, workflow, procedures.",
    register: "formal",
    examples: [
      { native: "We streamlined the onboarding process from two weeks to three days.", translation: "—", explanation: "Quantified before/after — the strongest way to use this verb.", whyUseful: "Exactly how to present process wins on a CV or in a review." },
      { native: "The new software streamlines communication between departments.", translation: "—", explanation: "Tool-as-subject construction, extremely common in product copy.", whyUseful: "Pattern for describing any tool's benefit." },
      { native: "Management wants to streamline approval workflows before Q4.", translation: "—", explanation: "Note the corporate time anchor 'before Q4'.", whyUseful: "Realistic sentence for meeting minutes and OKR documents." },
    ],
  }),
  card({
    id: "en-touch-base", languageId: "en-pro", deckIds: ["deck-en-meetings"],
    word: "touch base", translation: "to make brief contact to sync up",
    partOfSpeech: "idiom", cefr: "B2", topic: "Communication", difficulty: 2, frequency: 5,
    pronunciation: "tuch BAYS", ipa: "/tʌtʃ beɪs/",
    collocations: ["touch base with someone", "touch base on the project", "let's touch base next week"],
    synonyms: ["check in", "catch up", "sync up"], antonyms: [],
    relatedWords: ["follow up", "circle back", "loop in"],
    memoryTips: "From baseball: a runner must touch each base. In business, you briefly 'touch' each stakeholder.",
    commonMistakes: "It's 'touch base', never 'touch bases' or 'touch the base'. And it implies BRIEF contact — not a long meeting.",
    culturalNotes: "Beloved and mocked in equal measure — quintessential US corporate speak. Use it naturally, but don't stack it with other buzzwords.",
    usageNotes: "'Touch base with [person] on/about [topic]'.",
    register: "neutral",
    examples: [
      { native: "Let's touch base on Friday to review the launch plan.", translation: "—", explanation: "Proposing a short sync with a clear agenda.", whyUseful: "One of the five most common phrases in US work calendars." },
      { native: "I just wanted to touch base and see how the report is coming along.", translation: "—", explanation: "Softened check-in opener — polite pressure.", whyUseful: "The diplomatic way to chase a deliverable without nagging." },
      { native: "She touched base with the client before finalizing the proposal.", translation: "—", explanation: "Past tense narrative use.", whyUseful: "Shows the idiom conjugates like a normal verb phrase." },
    ],
  }),
  card({
    id: "en-mitigate", languageId: "en-pro", deckIds: ["deck-en-negotiation"],
    word: "mitigate", translation: "to make less severe or harmful",
    partOfSpeech: "verb", cefr: "C1", topic: "Risk", difficulty: 3, frequency: 4,
    pronunciation: "MIT-ih-gayt", ipa: "/ˈmɪt.ɪ.ɡeɪt/",
    collocations: ["mitigate risk", "mitigate the impact", "mitigating circumstances"],
    synonyms: ["alleviate", "reduce", "lessen"], antonyms: ["aggravate", "exacerbate"],
    relatedWords: ["mitigation", "risk assessment", "contingency"],
    memoryTips: "MITigate = make it a MITe (tiny bit) less bad. Its evil twin is exacerbate.",
    commonMistakes: "'Mitigate against' is a famous error — you mitigate risk, you militate against something. Also: mitigate reduces harm, it doesn't eliminate it.",
    usageNotes: "The default verb in risk management, law ('mitigating circumstances'), and climate policy.",
    register: "formal",
    examples: [
      { native: "We implemented backups to mitigate the risk of data loss.", translation: "—", explanation: "Action + 'to mitigate the risk of' + bad outcome.", whyUseful: "The standard structure of every risk-register entry." },
      { native: "The judge considered several mitigating circumstances.", translation: "—", explanation: "Legal fixed phrase: factors reducing culpability.", whyUseful: "Essential for understanding legal and HR contexts." },
      { native: "Diversifying suppliers mitigates our exposure to shortages.", translation: "—", explanation: "Gerund subject + present simple — analytic writing style.", whyUseful: "Model sentence for strategy memos and consulting decks." },
    ],
  }),
  card({
    id: "en-stakeholder", languageId: "en-pro", deckIds: ["deck-en-meetings"],
    word: "stakeholder", translation: "anyone with an interest in a project's outcome",
    partOfSpeech: "noun", cefr: "B2", topic: "Business Strategy", difficulty: 2, frequency: 5,
    pronunciation: "STAYK-hohl-der", ipa: "/ˈsteɪkˌhoʊl.dər/", plural: "stakeholders",
    collocations: ["key stakeholders", "stakeholder buy-in", "align stakeholders"],
    synonyms: ["interested party"], antonyms: [],
    relatedWords: ["shareholder", "buy-in", "alignment"],
    memoryTips: "Someone holding a 'stake' (a bet) on your project's outcome — they win or lose with you.",
    commonMistakes: "Stakeholder ≠ shareholder. Shareholders own stock; stakeholders include employees, customers, regulators — anyone affected.",
    usageNotes: "'Stakeholder buy-in' (their agreement/support) is the phrase you'll hear most.",
    register: "formal",
    examples: [
      { native: "We need buy-in from all key stakeholders before proceeding.", translation: "—", explanation: "'Buy-in' = agreement and support; 'key' = the important ones.", whyUseful: "Possibly the most-spoken sentence in project management." },
      { native: "The redesign affects internal and external stakeholders differently.", translation: "—", explanation: "The internal/external stakeholder split is a standard analysis lens.", whyUseful: "Frames impact analysis the way consultants do." },
      { native: "She mapped the stakeholders by influence and interest.", translation: "—", explanation: "References the influence/interest matrix, a classic PM tool.", whyUseful: "Signals real project-management literacy in interviews." },
    ],
  }),
];
