import { card } from "./builder";

export const ES_CARDS = [
  card({
    id: "es-madrugar", languageId: "es", deckIds: ["deck-es-daily"],
    word: "madrugar", translation: "to wake up very early",
    partOfSpeech: "verb", cefr: "B1", topic: "Daily Life", difficulty: 3, frequency: 3,
    pronunciation: "mah-droo-GAR", ipa: "/ma.ðɾuˈɣaɾ/",
    conjugations: [
      { tense: "Presente", forms: { yo: "madrugo", tú: "madrugas", "él/ella": "madruga", nosotros: "madrugamos", vosotros: "madrugáis", "ellos/ellas": "madrugan" } },
      { tense: "Pretérito", forms: { yo: "madrugué", tú: "madrugaste", "él/ella": "madrugó", nosotros: "madrugamos", vosotros: "madrugasteis", "ellos/ellas": "madrugaron" } },
    ],
    irregularForms: ["yo madrugué (spelling change g→gu)"],
    collocations: ["madrugar mucho", "no me gusta madrugar"],
    synonyms: ["levantarse temprano"], antonyms: ["trasnochar"],
    relatedWords: ["la madrugada", "el madrugón"],
    memoryTips: "'La madrugada' is the early morning — madrugar is living in it. One Spanish verb for a whole English phrase.",
    commonMistakes: "There's no direct English equivalent, so learners say 'despertar temprano'. Natives just say 'madrugar'.",
    culturalNotes: "Famous proverb: 'A quien madruga, Dios le ayuda' — the early bird catches the worm.",
    grammarNotes: "Regular -ar verb except the yo-pretérito spelling change (madrugué).",
    register: "neutral",
    examples: [
      { native: "Mañana tengo que madrugar para coger el tren.", translation: "Tomorrow I have to get up early to catch the train.", explanation: "'Tener que + infinitive' expresses obligation.", whyUseful: "An everyday sentence pattern you'll reuse constantly." },
      { native: "No me gusta nada madrugar los domingos.", translation: "I really hate getting up early on Sundays.", explanation: "'No me gusta nada' intensifies the dislike.", whyUseful: "Natural way to complain — instant conversation material." },
      { native: "A quien madruga, Dios le ayuda.", translation: "God helps those who rise early. (The early bird catches the worm.)", explanation: "A classic refrán (proverb) every native knows.", whyUseful: "Quoting proverbs makes you sound impressively fluent." },
    ],
  }),
  card({
    id: "es-presupuesto", languageId: "es", deckIds: ["deck-es-travel"],
    word: "el presupuesto", translation: "budget / quote",
    partOfSpeech: "noun", cefr: "B1", topic: "Money", difficulty: 3, frequency: 4,
    pronunciation: "preh-soo-PWES-toh", ipa: "/pɾe.suˈpwes.to/", gender: "masculine", plural: "los presupuestos",
    collocations: ["ajustarse al presupuesto", "pedir un presupuesto", "presupuesto ajustado"],
    synonyms: ["el cálculo de gastos"], antonyms: [],
    relatedWords: ["presupuestar", "los gastos", "la factura"],
    memoryTips: "Pre-supuesto = 'pre-supposed' money — what you suppose you'll spend before you spend it.",
    commonMistakes: "It means both 'budget' AND 'a quote from a contractor'. 'Pedir un presupuesto' = ask for a quote, not ask for a budget.",
    usageNotes: "In shops/services, asking '¿Me puede hacer un presupuesto?' gets you a written estimate.",
    register: "neutral",
    examples: [
      { native: "Viajamos con un presupuesto muy ajustado.", translation: "We're traveling on a very tight budget.", explanation: "'Ajustado' (tight) is the go-to adjective with presupuesto.", whyUseful: "Essential for negotiating prices while traveling." },
      { native: "¿Me puede hacer un presupuesto para la reparación?", translation: "Can you give me a quote for the repair?", explanation: "Here presupuesto = written estimate.", whyUseful: "Exactly what you say at a mechanic or repair shop in Spain." },
      { native: "El gobierno aprobó el presupuesto anual.", translation: "The government approved the annual budget.", explanation: "Formal/political register of the same word.", whyUseful: "You'll hear this constantly in Spanish news." },
    ],
  }),
  card({
    id: "es-sobremesa", languageId: "es", deckIds: ["deck-es-daily"],
    word: "la sobremesa", translation: "after-meal table talk",
    partOfSpeech: "noun", cefr: "B2", topic: "Culture", difficulty: 2, frequency: 3,
    pronunciation: "soh-breh-MEH-sah", ipa: "/so.βɾeˈme.sa/", gender: "feminine", plural: "las sobremesas",
    collocations: ["hacer sobremesa", "una larga sobremesa"],
    synonyms: [], antonyms: [],
    relatedWords: ["la mesa", "la comida", "charlar"],
    memoryTips: "Sobre-mesa = 'over the table' — the time you stay chatting over the table after eating.",
    commonMistakes: "Untranslatable — don't try to force an English equivalent; explain it instead.",
    culturalNotes: "A sacred Spanish institution: lunches can extend an hour or more just in sobremesa. Leaving right after eating can seem cold.",
    register: "neutral",
    examples: [
      { native: "La sobremesa duró más que la propia comida.", translation: "The after-meal chat lasted longer than the meal itself.", explanation: "'La propia comida' = the meal itself.", whyUseful: "Perfectly captures a beloved Spanish custom." },
      { native: "Nos quedamos de sobremesa hasta las seis.", translation: "We stayed chatting at the table until six.", explanation: "'Quedarse de sobremesa' = to linger after the meal.", whyUseful: "Natural collocation natives actually use." },
      { native: "El café de la sobremesa es una tradición española.", translation: "The after-lunch coffee is a Spanish tradition.", explanation: "Sobremesa used as a modifier of café.", whyUseful: "Cultural literacy that impresses native speakers." },
    ],
  }),
  card({
    id: "es-quedar", languageId: "es", deckIds: ["deck-es-daily"],
    word: "quedar", translation: "to meet up / to remain / to suit",
    partOfSpeech: "verb", cefr: "B1", topic: "Social", difficulty: 4, frequency: 5,
    pronunciation: "keh-DAR", ipa: "/keˈðaɾ/",
    conjugations: [
      { tense: "Presente", forms: { yo: "quedo", tú: "quedas", "él/ella": "queda", nosotros: "quedamos", vosotros: "quedáis", "ellos/ellas": "quedan" } },
    ],
    collocations: ["quedar con amigos", "quedar bien", "quedarse en casa"],
    synonyms: ["verse", "permanecer"], antonyms: [],
    relatedWords: ["quedarse", "la quedada"],
    memoryTips: "One verb, three lives: quedar CON someone = meet up; quedar + adjective = turn out; quedarSE = stay.",
    commonMistakes: "Confusing 'quedar' (meet/remain) with 'quedarse' (stay). '¿Quedamos?' = shall we meet? — NOT 'shall we stay?'.",
    grammarNotes: "Reflexive 'quedarse' changes the meaning to 'to stay'. 'Me queda bien' = it fits me well.",
    usageNotes: "'¿Quedamos a las ocho?' is THE way to arrange meetups in Spain.",
    register: "casual",
    examples: [
      { native: "¿Quedamos el viernes para tomar algo?", translation: "Shall we meet up on Friday for a drink?", explanation: "'Quedar para + infinitive' = arrange to do something.", whyUseful: "The standard sentence for making plans with Spanish friends." },
      { native: "Me quedo en casa esta noche, estoy agotado.", translation: "I'm staying home tonight, I'm exhausted.", explanation: "Reflexive 'quedarse' = to stay.", whyUseful: "Contrasts the reflexive meaning so you never mix them up." },
      { native: "Esa chaqueta te queda genial.", translation: "That jacket looks great on you.", explanation: "'Quedar bien/mal a alguien' = to suit someone.", whyUseful: "A third, very common meaning — great for compliments." },
    ],
  }),
  card({
    id: "es-imprescindible", languageId: "es", deckIds: ["deck-es-travel"],
    word: "imprescindible", translation: "essential / indispensable",
    partOfSpeech: "adjective", cefr: "B2", topic: "Descriptions", difficulty: 3, frequency: 4,
    pronunciation: "eem-press-theen-DEE-bleh", ipa: "/im.pɾes.θinˈdi.βle/",
    collocations: ["requisito imprescindible", "es imprescindible que + subjuntivo"],
    synonyms: ["esencial", "indispensable", "fundamental"], antonyms: ["prescindible", "innecesario"],
    relatedWords: ["prescindir", "necesario"],
    memoryTips: "im-PRESCINDible = something you cannot 'prescind' (do without). The 'im-' blocks the letting go.",
    commonMistakes: "'Es imprescindible que' requires the subjunctive: 'que vengas', not 'que vienes'.",
    grammarNotes: "Triggers subjunctive in 'es imprescindible que...' constructions.",
    register: "neutral",
    examples: [
      { native: "Es imprescindible reservar con antelación en verano.", translation: "Booking in advance is essential in summer.", explanation: "Impersonal 'es imprescindible + infinitive'.", whyUseful: "Practical travel advice structure used on every booking site." },
      { native: "Es imprescindible que traigas el pasaporte.", translation: "It's essential that you bring your passport.", explanation: "With 'que' + subject, the subjunctive 'traigas' is mandatory.", whyUseful: "Trains the subjunctive trigger — a key B2 skill." },
      { native: "El español es un requisito imprescindible para este puesto.", translation: "Spanish is an essential requirement for this position.", explanation: "'Requisito imprescindible' is a fixed collocation in job ads.", whyUseful: "You'll see this exact phrase in every Spanish job posting." },
    ],
  }),
];
