import { card } from "./builder";

export const FR_CARDS = [
  card({
    id: "fr-entretien", languageId: "fr", deckIds: ["deck-fr-business"],
    word: "l'entretien", translation: "interview / maintenance",
    partOfSpeech: "noun", cefr: "B1", topic: "Business", difficulty: 3, frequency: 4,
    pronunciation: "lawn-truh-tyan", ipa: "/ɑ̃.tʁə.tjɛ̃/", gender: "masculine", plural: "les entretiens",
    collocations: ["passer un entretien", "entretien d'embauche", "entretien annuel"],
    synonyms: ["l'interview", "la conversation"], antonyms: [],
    relatedWords: ["embaucher", "le recrutement", "le candidat"],
    memoryTips: "Entre-tien = 'holding between' — two people holding a conversation between them.",
    commonMistakes: "Don't confuse with 'interview' (used only for media interviews in French). A job interview is always 'un entretien d'embauche'.",
    culturalNotes: "French job interviews tend to be formal; expect 'vous' throughout unless invited otherwise.",
    grammarNotes: "Masculine noun. 'Entretien' also means maintenance (l'entretien de la voiture).",
    usageNotes: "In professional contexts, 'entretien' nearly always means a formal meeting or interview.",
    register: "formal",
    examples: [
      { native: "J'ai un entretien d'embauche demain matin.", translation: "I have a job interview tomorrow morning.", explanation: "'Entretien d'embauche' is the fixed expression for a job interview.", whyUseful: "The single most common sentence you'll need when job hunting in France." },
      { native: "L'entretien annuel avec mon manager s'est bien passé.", translation: "The annual review with my manager went well.", explanation: "'Entretien annuel' = the yearly performance review.", whyUseful: "Essential corporate vocabulary for workplace conversations." },
      { native: "L'entretien de l'appartement est inclus dans le loyer.", translation: "The maintenance of the apartment is included in the rent.", explanation: "Same word, second meaning: upkeep/maintenance.", whyUseful: "Shows the double meaning so you're not confused when renting." },
    ],
  }),
  card({
    id: "fr-reunion", languageId: "fr", deckIds: ["deck-fr-business"],
    word: "la réunion", translation: "meeting",
    partOfSpeech: "noun", cefr: "A2", topic: "Business", difficulty: 2, frequency: 5,
    pronunciation: "ray-oon-yon", ipa: "/ʁe.y.njɔ̃/", gender: "feminine", plural: "les réunions",
    collocations: ["assister à une réunion", "organiser une réunion", "réunion d'équipe"],
    synonyms: ["l'assemblée", "le rendez-vous"], antonyms: [],
    relatedWords: ["se réunir", "la salle de réunion", "l'ordre du jour"],
    memoryTips: "Think 're-union' — people coming together again.",
    commonMistakes: "False friend alert: 'réunion' is a work meeting, not a 'reunion' of old friends (that's 'des retrouvailles').",
    grammarNotes: "Feminine noun.",
    usageNotes: "The default word for any work meeting.",
    register: "neutral",
    examples: [
      { native: "La réunion commence à neuf heures précises.", translation: "The meeting starts at nine o'clock sharp.", explanation: "'Précises' after a time means 'sharp/exactly'.", whyUseful: "Scheduling language you'll use daily at work." },
      { native: "Je ne peux pas, je suis en réunion.", translation: "I can't, I'm in a meeting.", explanation: "'Être en réunion' — no article needed.", whyUseful: "The classic polite excuse in French office life." },
      { native: "Nous devons organiser une réunion d'équipe la semaine prochaine.", translation: "We need to organize a team meeting next week.", explanation: "'Réunion d'équipe' = team meeting; note the 'de' contraction.", whyUseful: "Practical structure for proposing meetings." },
    ],
  }),
  card({
    id: "fr-se-debrouiller", languageId: "fr", deckIds: ["deck-fr-slang"],
    word: "se débrouiller", translation: "to manage / get by / figure it out",
    partOfSpeech: "verb", cefr: "B1", topic: "Daily Life", difficulty: 3, frequency: 4,
    pronunciation: "suh day-broo-yay", ipa: "/sə de.bʁu.je/",
    conjugations: [
      { tense: "Présent", forms: { je: "me débrouille", tu: "te débrouilles", "il/elle": "se débrouille", nous: "nous débrouillons", vous: "vous débrouillez", "ils/elles": "se débrouillent" } },
      { tense: "Passé composé", forms: { je: "me suis débrouillé(e)", tu: "t'es débrouillé(e)", "il/elle": "s'est débrouillé(e)", nous: "nous sommes débrouillé(e)s", vous: "vous êtes débrouillé(e)(s)", "ils/elles": "se sont débrouillé(e)s" } },
    ],
    collocations: ["se débrouiller tout seul", "se débrouiller en français"],
    synonyms: ["s'arranger", "gérer"], antonyms: ["échouer"],
    relatedWords: ["débrouillard", "la débrouille"],
    memoryTips: "'Dé-brouiller' = to un-fog. When you 'se débrouilles', you clear the fog around a problem yourself.",
    commonMistakes: "Learners forget it's reflexive — 'je débrouille' is wrong; you must say 'je me débrouille'.",
    culturalNotes: "Being 'débrouillard' (resourceful) is a genuinely admired trait in French culture.",
    grammarNotes: "Reflexive verb, conjugated with être in compound tenses.",
    usageNotes: "Perfect answer to 'Tu parles français ?' → 'Je me débrouille' (I get by).",
    register: "casual",
    examples: [
      { native: "Ne t'inquiète pas, je vais me débrouiller.", translation: "Don't worry, I'll manage.", explanation: "Future proche with reflexive pronoun before the infinitive.", whyUseful: "Everyday phrase to reassure someone you don't need help." },
      { native: "Elle se débrouille très bien en espagnol.", translation: "She gets by very well in Spanish.", explanation: "'Se débrouiller en + language' = to get by in a language.", whyUseful: "The natural, modest way to describe language ability." },
      { native: "Débrouille-toi, ce n'est pas mon problème !", translation: "Figure it out yourself, it's not my problem!", explanation: "Imperative form; the pronoun moves after the verb.", whyUseful: "Common (blunt) spoken French you'll hear in real life." },
    ],
  }),
  card({
    id: "fr-echeance", languageId: "fr", deckIds: ["deck-fr-business"],
    word: "l'échéance", translation: "deadline / due date",
    partOfSpeech: "noun", cefr: "B2", topic: "Business", difficulty: 4, frequency: 3,
    pronunciation: "ay-shay-awnss", ipa: "/e.ʃe.ɑ̃s/", gender: "feminine", plural: "les échéances",
    collocations: ["respecter une échéance", "repousser l'échéance", "à brève échéance"],
    synonyms: ["la date limite", "le délai"], antonyms: [],
    relatedWords: ["échoir", "le calendrier", "le délai"],
    memoryTips: "Échéance sounds like 'ess-CHANCE' — your last chance before time runs out.",
    commonMistakes: "'Délai' means the time period allowed; 'échéance' is the end date itself. Saying 'le délai est vendredi' is a common learner error.",
    grammarNotes: "Feminine noun starting with a vowel → l'échéance.",
    usageNotes: "More formal than 'date limite'; preferred in contracts and finance.",
    register: "formal",
    examples: [
      { native: "Nous devons absolument respecter l'échéance du 15 mars.", translation: "We absolutely must meet the March 15 deadline.", explanation: "'Respecter une échéance' = to meet a deadline.", whyUseful: "Core project-management phrasing for professional emails." },
      { native: "L'échéance du prêt arrive à la fin du mois.", translation: "The loan payment is due at the end of the month.", explanation: "In finance, 'échéance' means an installment's due date.", whyUseful: "You'll see this word on every French bank document." },
      { native: "À long terme, cette stratégie sera rentable, mais l'échéance est lointaine.", translation: "In the long run this strategy will pay off, but the horizon is distant.", explanation: "Figurative use for a time horizon.", whyUseful: "Elevates your French in analytical discussions." },
    ],
  }),
  card({
    id: "fr-carrement", languageId: "fr", deckIds: ["deck-fr-slang"],
    word: "carrément", translation: "totally / straight up",
    partOfSpeech: "adverb", cefr: "B1", topic: "Slang", difficulty: 2, frequency: 4,
    pronunciation: "kah-ray-mawn", ipa: "/ka.ʁe.mɑ̃/",
    collocations: ["carrément génial", "y aller carrément"],
    synonyms: ["complètement", "franchement"], antonyms: ["à peine"],
    relatedWords: ["carré", "franchement"],
    memoryTips: "From 'carré' (square) — squarely, 100%, no corners cut.",
    commonMistakes: "Too casual for formal writing; don't use it in a cover letter.",
    culturalNotes: "As a one-word reply, 'Carrément !' means 'Totally!' — very common among younger speakers.",
    usageNotes: "Softens or intensifies depending on tone; standalone it's enthusiastic agreement.",
    register: "casual",
    examples: [
      { native: "Ce film était carrément incroyable.", translation: "That movie was totally incredible.", explanation: "Intensifier before an adjective.", whyUseful: "Instantly makes your spoken French sound natural." },
      { native: "— Tu viens ce soir ? — Carrément !", translation: "— Coming tonight? — Totally!", explanation: "Standalone enthusiastic 'yes'.", whyUseful: "One of the most common casual replies in France." },
      { native: "Il a carrément quitté la réunion sans rien dire.", translation: "He straight up left the meeting without saying anything.", explanation: "Here it marks something surprising/blunt.", whyUseful: "Shows the 'boldness' nuance beyond just 'totally'." },
    ],
  }),
  card({
    id: "fr-neanmoins", languageId: "fr", deckIds: ["deck-fr-business"],
    word: "néanmoins", translation: "nevertheless / nonetheless",
    partOfSpeech: "adverb", cefr: "B2", topic: "Connectors", difficulty: 3, frequency: 3,
    pronunciation: "nay-awn-mwan", ipa: "/ne.ɑ̃.mwɛ̃/",
    collocations: ["il n'en demeure pas moins que", "néanmoins, il faut"],
    synonyms: ["cependant", "toutefois", "pourtant"], antonyms: ["donc", "par conséquent"],
    relatedWords: ["malgré", "bien que"],
    memoryTips: "né-an-moins = 'not-any-less' → 'none the less'. The English is hiding inside the French.",
    commonMistakes: "Learners overuse 'mais'. Swapping in 'néanmoins' at B2 level is what examiners want to hear.",
    grammarNotes: "Usually sentence-initial followed by a comma, or after the verb.",
    usageNotes: "Formal register; in speech, 'quand même' or 'pourtant' are more natural.",
    register: "formal",
    examples: [
      { native: "Le projet est risqué ; néanmoins, nous allons le financer.", translation: "The project is risky; nevertheless, we will fund it.", explanation: "Classic concessive structure joining two clauses.", whyUseful: "Exactly the connector DELF/DALF graders reward." },
      { native: "Il était fatigué. Il a néanmoins terminé le rapport.", translation: "He was tired. He nonetheless finished the report.", explanation: "Post-verbal position — slightly more literary.", whyUseful: "Shows flexible placement in formal writing." },
      { native: "Les résultats sont encourageants, néanmoins insuffisants.", translation: "The results are encouraging, yet insufficient.", explanation: "Elliptical use directly before an adjective.", whyUseful: "Compact structure common in business reports." },
    ],
  }),
];
